server:server.cpp
	g++ -o server server.cpp server_trans_controller.cpp reader/data_reader.cpp reader/remote_data_reader.cpp reader/session.cpp writer/data_writer.cpp writer/file_data_writer.cpp -I reader -I writer -I .. -lpthread
	